# Generated by Django 3.1.4 on 2021-01-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('UserType', models.CharField(choices=[('Guest', 'Guest'), ('Admin', 'Admin')], default='user', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
